// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection -- pooled connections
    // (through PgBouncer) don't reliably support the locking Prisma Migrate
    // uses. Locally there's no pooler, so DATABASE_URL_UNPOOLED is unset and
    // this just falls back to the regular DATABASE_URL.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
